---
  - name: Add deployment user
    user:
      name: '{{ deploy_user }}'
      groups: '{{ deploy_user }}'
      shell: /bin/bash
    become: true

  - name: Add sudo group rights for deployment user
    lineinfile:
      dest: /etc/sudoers
      regexp: '^{{ deploy_user }}'
      line: '{{ deploy_user }} ALL=(ALL) NOPASSWD: ALL'
      state: present
      validate: 'visudo -cf %s'
    become: true

  - name: Set user key
    authorized_key:
      user: '{{ deploy_user }}'
      state: present
      exclusive: True
      key: '{{ item }}'
    with_file:
      - '{{ authorized_key_file }}'