---
- name: Ensure unattended-upgrades is installed
  apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: yes
  become: true

- name: Ensure apt-listchanges is installed
  apt:
    pkg: apt-listchanges
    state: present
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: yes
  become: true

- name: Configure APT auto-upgrades
  lineinfile:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^APT::Periodic::Update-Package-Lists"
      line: 'APT::Periodic::Update-Package-Lists \"1\";'
    - regexp: "^APT::Periodic::Unattended-Upgrade"
      line: 'APT::Periodic::Unattended-Upgrade \"1\";'
  notify: restart unattended-upgrades
  become: true

- name: Ensure unattended-upgrades is running
  service:
    name: unattended-upgrades
    state: started
  become: true

# TODO: more 'conscious' config so that I know when it runs and what it does