---
- name: Ensure mailutils is installed
  apt:
    pkg: mailutils
    state: present
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: yes

- name: Add notification script
  template:
    src: etc/ssh/login-notify.sh.j2
    dest: /etc/ssh/login-notify.sh
    mode: a+x
  register: login_notify

- name: Add script to /etc/pam.d/sshd
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: "^session optional pam_exec.so seteuid /etc/ssh/login-notify.sh$"
    line: "session optional pam_exec.so seteuid /etc/ssh/login-notify.sh"
    state: present
  register: login_notify

- name: Restart ssh if config changed
  service:
    name: ssh
    state: reloaded
  when: login_notify.changed == True