---
- name: Ensure UFW is installed
  apt:
    pkg: ufw
    state: present
    cache_valid_time: "{{ cache_valid_time }}"
    update_cache: yes
  become: true

- name: Ensure UFW logging is on
  ufw:
    logging: 'low'
  become: true

- name: Reset UFW configuraton
  ufw:
    state: reset
  when: force_ufw_reset is defined and force_ufw_reset is True

- name: Ensure UFW denies incoming connections by default
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  become: true

- name: Ensure UFW allows outgoing connections by default
  ufw:
    state: enabled
    direction: outgoing
    policy: allow
    become: true

- name: Ensure SSH traffic is limited
  ufw:
    rule: limit
    from_ip: "{{ ssh_allowed_ip }}"
    port: "{{ ssh_port | int }}"
    proto: tcp
    comment: 'SSH'
  become: true

- name: Ensure group-wide rules are applied
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items: "{{ ufw_rules_group }}"
  become: true

- name: Ensure host-specific rules are applied
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
  with_items: "{{ ufw_rules_host }}"
  when: 
    - ufw_rules_host is defined
    - ufw_rules_host is iterable
  become: true

- name: Ensure UFW is enabled
  ufw:
    state: enabled
  become: true